# Generated by Django 4.2.2 on 2023-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("fullname", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=500)),
                ("password", models.CharField(max_length=500)),
                ("profilepicture", models.ImageField(upload_to="media")),
            ],
        ),
    ]
